// from: https://github.com/metno/weathericons/tree/main/weather

export default [
  {
    symbol: 'clearsky',
    english: 'Clear sky',
    bokmål: 'Klarvær',
    nynorsk: 'Klårvêr',
  },
  {
    symbol: 'fair',
    english: 'Fair',
    bokmål: 'Lettskyet',
    nynorsk: 'Lettskya',
  },
  {
    symbol: 'partlycloudy',
    english: 'Partly cloudy',
    bokmål: 'Delvis skyet',
    nynorsk: 'Delvis skya',
  },
  {
    symbol: 'cloudy',
    english: 'Cloudy',
    bokmål: 'Skyet',
    nynorsk: 'Skya',
  },
  {
    symbol: 'lightrainshowers',
    english: 'Light rain showers',
    bokmål: 'Lette regnbyger',
    nynorsk: 'Lette regnbyer',
  },
  {
    symbol: 'rainshowers',
    english: 'Rain showers',
    bokmål: 'Regnbyger',
    nynorsk: 'Regnbyer',
  },
  {
    symbol: 'heavyrainshowers',
    english: 'Heavy rain showers',
    bokmål: 'Kraftige regnbyger',
    nynorsk: 'Kraftige regnbyer',
  },
  {
    symbol: 'lightrainshowersandthunder',
    english: 'Light rain showers and thunder',
    bokmål: 'Lette regnbyger og torden',
    nynorsk: 'Lette regnbyer og torevêr',
  },
  {
    symbol: 'rainshowersandthunder',
    english: 'Rain showers and thunder',
    bokmål: 'Regnbyger og torden',
    nynorsk: 'Regnbyer og torevêr',
  },
  {
    symbol: 'heavyrainshowersandthunder',
    english: 'Heavy rain showers and thunder',
    bokmål: 'Kraftige regnbyger og torden',
    nynorsk: 'Kraftige regnbyer og torevêr',
  },
  {
    symbol: 'lightsleetshowers',
    english: 'Light sleet showers',
    bokmål: 'Lette sluddbyger',
    nynorsk: 'Lette sluddbyer',
  },
  {
    symbol: 'sleetshowers',
    english: 'Sleet showers',
    bokmål: 'Sluddbyger',
    nynorsk: 'Sluddbyer',
  },
  {
    symbol: 'heavysleetshowers',
    english: 'Heavy sleet showers',
    bokmål: 'Kraftige sluddbyger',
    nynorsk: 'Kraftige sluddbyer',
  },
  {
    symbol: 'lightssleetshowersandthunder',
    english: 'Light sleet showers and thunder',
    bokmål: 'Lette sluddbyger og torden',
    nynorsk: 'Lette sluddbyer og torevêr',
  },
  {
    symbol: 'sleetshowersandthunder',
    english: 'Sleet showers and thunder',
    bokmål: 'Sluddbyger og torden',
    nynorsk: 'Sluddbyer og torevêr',
  },
  {
    symbol: 'heavysleetshowersandthunder',
    english: 'Heavy sleet showers and thunder',
    bokmål: 'Kraftige sluddbyger og torden',
    nynorsk: 'Kraftige sluddbyer og torevêr',
  },
  {
    symbol: 'lightsnowshowers',
    english: 'Light snow showers',
    bokmål: 'Lette snøbyger',
    nynorsk: 'Lette snøbyer',
  },
  {
    symbol: 'snowshowers',
    english: 'Snow showers',
    bokmål: 'Snøbyger',
    nynorsk: 'Snøbyer',
  },
  {
    symbol: 'heavysnowshowers',
    english: 'Heavy snow showers',
    bokmål: 'Kraftige snøbyger',
    nynorsk: 'Kraftige snøbyer',
  },
  {
    symbol: 'lightssnowshowersandthunder',
    english: 'Light snow showers and thunder',
    bokmål: 'Lette snøbyger og torden',
    nynorsk: 'Lette snøbyer og torevêr',
  },
  {
    symbol: 'snowshowersandthunder',
    english: 'Snow showers and thunder',
    bokmål: 'Snøbyger og torden',
    nynorsk: 'Snøbyer og torevêr',
  },
  {
    symbol: 'heavysnowshowersandthunder',
    english: 'Heavy snow showers and thunder',
    bokmål: 'Kraftige snøbyger og torden',
    nynorsk: 'Kraftige snøbyer og torevêr',
  },
  {
    symbol: 'lightrain',
    english: 'Light rain',
    bokmål: 'Lett regn',
    nynorsk: 'Lett regn',
  },
  {
    symbol: 'rain',
    english: 'Rain',
    bokmål: 'Regn',
    nynorsk: 'Regn',
  },
  {
    symbol: 'heavyrain',
    english: 'Heavy rain',
    bokmål: 'Kraftig regn',
    nynorsk: 'Kraftig regn',
  },
  {
    symbol: 'lightrainandthunder',
    english: 'Light rain and thunder',
    bokmål: 'Lett regn og torden',
    nynorsk: 'Lett regn og torevêr',
  },
  {
    symbol: 'rainandthunder',
    english: 'Rain and thunder',
    bokmål: 'Regn og torden',
    nynorsk: 'Regn og torevêr',
  },
  {
    symbol: 'heavyrainandthunder',
    english: 'Heavy rain and thunder',
    bokmål: 'Kraftig regn og torden',
    nynorsk: 'Kraftig regn og torevêr',
  },
  {
    symbol: 'lightsleet',
    english: 'Light sleet',
    bokmål: 'Lett sludd',
    nynorsk: 'Lett sludd',
  },
  {
    symbol: 'sleet',
    english: 'Sleet',
    bokmål: 'Sludd',
    nynorsk: 'Sludd',
  },
  {
    symbol: 'heavysleet',
    english: 'Heavy sleet',
    bokmål: 'Kraftig sludd',
    nynorsk: 'Kraftig sludd',
  },
  {
    symbol: 'lightsleetandthunder',
    english: 'Light sleet and thunder',
    bokmål: 'Lett sludd og torden',
    nynorsk: 'Lett sludd og torevêr',
  },
  {
    symbol: 'sleetandthunder',
    english: 'Sleet and thunder',
    bokmål: 'Sludd og torden',
    nynorsk: 'Sludd og torevêr',
  },
  {
    symbol: 'heavysleetandthunder',
    english: 'Heavy sleet and thunder',
    bokmål: 'Kraftig sludd og torden',
    nynorsk: 'Kraftig sludd og torevêr',
  },
  {
    symbol: 'lightsnow',
    english: 'Light snow',
    bokmål: 'Lett snø',
    nynorsk: 'Lett snø',
  },
  {
    symbol: 'snow',
    english: 'Snow',
    bokmål: 'Snø',
    nynorsk: 'Snø',
  },
  {
    symbol: 'heavysnow',
    english: 'Heavy snow',
    bokmål: 'Kraftig snø',
    nynorsk: 'Kraftig snø',
  },
  {
    symbol: 'lightsnowandthunder',
    english: 'Light snow and thunder',
    bokmål: 'Lett snø og torden',
    nynorsk: 'Lett snø og torevêr',
  },
  {
    symbol: 'snowandthunder',
    english: 'Snow and thunder',
    bokmål: 'Snø og torden',
    nynorsk: 'Snø og torevêr',
  },
  {
    symbol: 'heavysnowandthunder',
    english: 'Heavy snow and thunder',
    bokmål: 'Kraftig snø og torden',
    nynorsk: 'Kraftig snø og torevêr',
  },
  {
    symbol: 'fog',
    english: 'Fog',
    bokmål: 'Tåke',
    nynorsk: 'Skodde',
  },
]
